language: cpp
sudo: required
dist: bionic
compiler:
  - g++
  - gcc
install:
  - sudo apt-get install cmake

before_install:
  - chmod +x build.sh
script:
  - sudo apt-get install libelfin-dev
  - gcc -v && g++ -v && cmake --version
  - ./build.sh